spring:
  application:
    name: ai-code-review-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_code_review
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ai_code_review
    user: user
    password: password
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL:qwen2.5-coder:7b}
          temperature: 0.2
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  storage:
    location: storage/projects

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
